# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9aced9aa1ba18e981c54bec2e58d3c240197b051ba391ee6a3f01e03a42b47f3bbf621e8fe4535b28dc5a45393809bbe50d90639ca60f07ff87ffa583538a8f5

test:
  secret_key_base: fed1fbcda57ae4828c47d6ded958ce3d18a30ad204730c20d7f51fe7771f31b897d381f1f1645467c166afca587c778f9c7a071f3a0b7e91ce3535fd01ac0fca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
